server:
  port: 8201
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: fs-user
          uri: lb://fs-user
          predicates:
            - Path=/fs-user/**
          filters:
            - StripPrefix=1
        - id: fs-cache
          uri: lb://fs-cache
          predicates:
            - Path=/fs-cache/**
          filters:
            - StripPrefix=1

secure:
  ignores:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"

