server:
  port: 8089
spring:
  application:
    name: fs-user
  profiles:
    active: dev #默认为开发环境
  config:
    location: classpath:/

fs:
  config:
    location: /conf

mybatis:
  configLocation: classpath:conf/mybatis.xml
  mapper-locations:
    - classpath:mapper/mysql/*.xml
    - classpath*:mapper/mysql/*.xml
