server:
  port: 8089
spring:
  application:
    name: fs-user
  profiles:
    active: dev #默认为开发环境
  config:
    location: classpath:/
  datasource:
#    url: jdbc:mysql://localhost:3306/fsdata?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root
    url: jdbc:mysql://nacos:3306/fsdata?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

fs:
  config:
    location: /conf

mybatis:
  configLocation: classpath:conf/mybatis.xml
  mapper-locations:
    - classpath:mapper/mysql/*.xml
    - classpath*:mapper/mysql/*.xml
