server:
  port: 8093
  version: v0.1
  servlet:
    session:
      cookie:
        secure: true
        path: /
        http-only: true
      timeout: 1000m #session超时时间
  tomcat:
    # 最大可被连接数
    max-connections: 10000
    # 等待队列长度
    accept-count: 1000

spring:
  application:
    name: fs-workflow
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  config:
    location: classpath:/
fs:
  config:
    location: /conf

mybatis:
  configLocation: classpath:conf/mybatis.xml
  mapper-locations:
    - classpath:mapper/mysql/*.xml
    - classpath*:mapper/mysql/*.xml

feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 60000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 60000 #服务请求处理超时时间（毫秒）

#  client:
#    config:
#      default:
#        connect-timeout: 600000
#        read-timeout: 600000

#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 30000

