REPLACE INTO `fs_sys_user` (`USER_CODE`, `USER_NAME`, `MOBILE`, `PHONE`, `EMAIL`, `ADDRESS`, `USER_TYPE`, `LAST_LOGIN_TIME`, `CANCEL_DATE`, `GMT_CREATED`, `GMT_MODIFIED`, `CREATOR`, `OPERATOR`, `USER_STATUS`, `LOCK_STATUS`, `USER_PWD`, `CARD_TYPE`, `CARD_NO`, `REMARK`) VALUES
	('admin', '管理员', '1', '1', '123@163.com', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '123', NULL, NULL, NULL);






